:toc: macro
:toc-title:
toc::[]

= Kiali.io
This repository contains the source code for https://kiali.io website.

The website is written in link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc], generated using link:https://gohugo.io/[Hugo], and hosted on GitHub.

== Requirements

Kiali.io runs on top of Hugo. In order to locally run a kiali.io instance you will need to either install Hugo and AsciiDoctor locally or run a docker image that contains Hugo and AsciiDoctor.

=== Install and Run Hugo and AsciiDoctor Locally

If you want to locally install the required tools, you first must have link://https://gohugo.io/[Hugo] installed and the `hugo` command available on your PATH. It is likely you can easily install `hugo` using your system's package manager. For more information about how to install Hugo please see its link:https://gohugo.io/getting-started/installing/[installation documentation].

Asciidoctor is also required to run kiali.io. The `make install` command will install Asciidoctor using link:https://rubygems.org[Ruby Gem] and Bundler. You will need to have the `gem` command on your path. Please see the link:https://rubygems.org/pages/download[Ruby Gem installation docs] for more information.

It is recommended to install and run at least **Hugo 0.48**

=== Install and Run Hugo and AsciiDoctor via Docker

If you do not want to install a local copy of Hugo and AsciiDoctor, you can run a Hugo+AsciiDoctor docker image instead. You need to first create the docker image via `make hugo-docker`. Once you have a docker image, you can run the Hugo server via `make hugo-serve`.

== Installing

If you want to install and run Hugo and AsciiDoctor locally, the following command needs to be run in order to install a few dependencies:

[source, bash]
----
make install
----

==  Start local server

Hugo has a live `serve` command that runs a small, lightweight web server on your computer so you can test your site locally without needing to upload it anywhere.  As you make changes to files in your project, it will rebuild your project and reload the browser for you.

[source,bash]
----
make serve
----

If you did not install Hugo and AsciiDoctor locally, but you instead want to run with the docker image, you can use the hugo-serve make target instead:

[source,bash]
----
make hugo-serve
----

If everything is working as expected you should see something like the following being outputted:

```
                   | EN
+------------------+-----+
  Pages            |  12
  Paginator pages  |   0
  Non-page files   |   0
  Static files     | 804
  Processed images |   0
  Aliases          |   0
  Sitemaps         |   1
  Cleaned          |   0

Total in 4798 ms
Watching for changes in /home/theute/Projects/Kiali/kiali.io/{content,data,layouts,static,themes}
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

You should now be able to access hugo running kiali.io at link:http://localhost:1313/[http://localhost:1313]

This running instance should support live reload. Changes you make to files should be automatically updated in your running instance.

Some files may not be supported for live reload. If you are not automatically seeing your changes live you may need to restart the server. You can restart the server by pressing 'ctrl-c' and running `make serve` again (or `make hugo-serve` if you are running the docker image).

==  Project directory structure

```
├── [archetypes]- Directory where you define the content, tags, categories, etc.
├── [content] - Directory that contains the content of the site.
│   ├── [contribute]
│   ├── [documentation]
├── [data] - Directory that contains site data such as localization configuration.
├── [layouts] - Directory that contains Go HTML/template library used to template and format the site.
├── [public] - (Doesn't exist until generated) Directory that contains the generated content for the site.  Should be part of your git.ignore file.
├── [scripts] - Directory that contains the generator for swagger documentation
├── [static] - Directory for any static files to be compiled into the web site (style sheets, JavaScript, images, robots.txt, fav icons, etc.).
├── [themes] - Directory that contains the site theme.  Themes override layouts.
├── Makefile
├── hugo/Dockerfile - the Dockerfile used to build the Hugo+AsciiDoctor image
├── config.toml - Main configuration file, where you define the web site title, URL, language, etc.
├── README.adoc (This file)
```

==  To generate the Swagger documentation
Run the following:
`sh scripts/build-swagger.sh`
