:toc: macro
:toc-title:
toc::[]

= Kiali.io
This repository contains the source code for https://kiali.io website.

The website is written in link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc], generated using [Hugo](https://gohugo.io/), and hosted on GitHub.

== Requirements

- You need Go & Bundler (Ruby)

== Building

- Clone this repository inside a GOPATH.  These instructions will use the example GOPATH of "/source/kiali/kiali" but you can use whatever you want. Just change the first line of the below instructions to use your GOPATH.

[source, bash]
----
export GOPATH=/source/kiali/kiali
mkdir -p $GOPATH
cd $GOPATH
mkdir -p src/github.com/kiali/kiali.io
git clone git@github.com:kiali/kiali.io
export PATH=${PATH}:${GOPATH}/bin
----

- Install Requirements

[source, bash]
----
make install
----

This will attempt to determine the binary of Hugo needed and download it. If it can't it will proceed to download the source code and compile.
You can force the compile by setting `BUILD_HUGO=TRUE`

[source, bash]
----
BUILD_HUGO=TRUE make install
----

You can always download the required dependencies yourself if the above fails:

 - Hugo at least v0.48 ([github releases](https://github.com/gohugoio/hugo/releases/tag/v0.48) or brew if you are on mac)
 - AsciiDoctor (by running `bundle install`)

==  Start local server

Hugo has a live `serve` command that runs a small, lightweight web server on your computer so you can test your site locally without needing to upload it anywhere.  As you make changes to files in your project, it will rebuild your project and reload the browser for you.

[source,bash]
----
make serve
----

```
                   | EN
+------------------+-----+
  Pages            |  12
  Paginator pages  |   0
  Non-page files   |   0
  Static files     | 804
  Processed images |   0
  Aliases          |   0
  Sitemaps         |   1
  Cleaned          |   0

Total in 4798 ms
Watching for changes in /home/theute/Projects/Kiali/kiali.io/{content,data,layouts,static,themes}
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

It should live reload. If not, you may have to restart the server.

==  Project directory structure

```
├── [archetypes]- Directory where you define the content, tags, categories, etc.
├── [content] - Directory that contains the content of the site.
│   ├── [api]
│   ├── [contribute]
│   ├── [features]
│   ├── [gettingstarted]
├── [data] - Directory that contains site data such as localization configuration.
├── [layouts] - Directory that contains Go HTML/template library used to template and format the site.
├── [public] - (Doesn't exist until generated) Directory that contains the generated content for the site.  Should be part of your git.ignore file.
├── [scripts] - Directory that contains the generator for swagger documentation
├── [static] - Directory for any static files to be compiled into the web site (style sheets, JavaScript, images, robots.txt, fav icons, etc.).
├── [themes] - Directory that contains the site theme.  Themes override layouts.
├── Makefile
├── config.toml - Main configuration file, where you define the web site title, URL, language, etc.
├── README.adoc (This file)
```

==  Add a new feature to be listed
`hugo new features/my-feature.adoc`

In the header, fill-in either the `youTubeID` or `image`, the template will use the YouTube ID if any and ignore `image`. The `youTubeId` looks like `NcxOapR7D0I`.
If you have an image rather than an YouTube video, add the image in: static/images/features (use the same name as the AsciiDoc file) and use: `features/my-feature.png` as the value for the `image` header

==  To generate the Swagger documentation
Run the following:
`sh scripts/build-swagger.sh`
