---
title: "Advanced installation options"
date: 2021-09-12T00:00:00+00:00
draft: false
weight: 40
---

:toc: macro
:toclevels: 4
:toc-title: In this section:
:keywords: Kiali Getting Started
:icons: font
:imagesdir: /images/gettingstarted/
:sectlinks:
:linkattrs:

toc::[]

== Installing a Kiali Server of a different version than the Operator

When you install the Kiali Operator, it will be configured to install a Kiali
Server that is the same version as the operator itself. For example, if you
have Kiali Operator v1.34.0 installed, that operator will install Kiali Server
v1.34.0. If you upgrade (or downgrade) the Kiali Operator, the operator will in
turn upgrade (or downgrade) the Kiali Server.

There are certain use-cases in which you want the Kiali Operator to install a
Kiali Server whose version is different than the operator version. Read the
following section _<<Using a custom image registry>>_ section to learn how to
configure this setup.

== Using a custom image registry

Kiali is released and published to the link:https://quay.io/[Quay.io container image registry]. There is a link:https://quay.io/repository/kiali/kiali-operator[repository hosting the Kiali operator images] and link:https://quay.io/repository/kiali/kiali[another one for the Kiali server images].

If you need to mirror the Kiali container images to some other registry, you still can use Helm to install the Kiali operator as follows:

[source,bash]
----
$ helm install \
    --namespace kiali-operator \
    --create-namespace \
    --set image.repo=your.custom.registry/owner/kiali-operator-repo
    --set image.tag=your_custom_tag
    --set allowAdHocKialiImage=true
    kiali-operator \
    kiali/kiali-operator
----

NOTE: Notice the `--set allowAdHocKialiImage=true` which allows specifying a
custom image in the Kiali CR. For security reasons, this is disabled by
default.

Then, when creating the Kiali CR, use the following attributes:

[source,yaml]
----
spec:
  deployment:
    image_name: your.custom.registry/owner/kiali-server-repo
    image_version: your_custom_tag
----


== Development Install

This option installs the _latest_ Kiali Operator and Kiali Server images which
are built from the master branches of Kiali GitHub repositories. This option is
good for demo and development installations.

[source,bash]
----
helm install \
  --set cr.create=true \
  --set cr.namespace=istio-system \
  --set cr.spec.deployment.image_version=latest \
  --set image.tag=latest \
  --namespace kiali-operator \
  -- create-namespace \
  kiali-operator \
  kiali/kiali-operator
----
