---
title: "Validation"
date: 2019-02-26T14:53:00+02:00
draft: false
type: "features/validation"
weight: 1
---

= Validation
:sectnums:
:toc: left
toc::[]
:toc-title: Validation
:keywords: Kiali Documentation
:icons: font
:imagesdir: /images/documentation/overview/

[#gateways]
== Gateways

=== Error message

More than one Gateway for the same host port combination

=== Description

Gateway creates a proxy that will forward the inbound traffic for the exposed ports. If two different gateways expose the same ports for the same host, this creates ambiquity inside Istio as either of these gateways could handle the traffic. This is most likely a configuration error. This check is done across all namespaces the user has access to. 

=== Resolution

Remove the duplicate gateway entries or merge the two gateway definitions into a single one. 

=== Severity

Warning

=== Example

[source, yaml]
----
include::/files/validation_examples/201.yaml
----

=== See Also

https://github.com/kiali/kiali/tree/master/business/checkers/gateways/multi_match_checker.go[Validator source code, window="_blank"]
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#Gateway[Istio Gateway documentation, window="_blank"]

'''

=== Error message

No matching workload found for gateway selector in this namespace

=== Description

A label selector to match the workload to which this gateway should be applied to. This validation will only check the current namespace for matching workloads as this is recommended (and potentially in the future required) by the Istio. Excluded from this check are the default "istio-ingressgateway" and "istio-egressgateway" workloads which Istio ships with.

Although your traffic might be correctly routed to a workload in other namespace, this is not a guaranteed behavior and thus a warning is flagged in such cases also.

=== Resolution

Deploy the missing workload or fix the selector to target a correct location. 

=== Severity

Warning

=== Example

[source, yaml]
----
<TODO REQUIRES EXAMPLE>
----

=== See Also

https://github.com/kiali/kiali/blob/master/business/checkers/gateways/selector_checker.go[Validator source code, window="_blank"]
https://istio.io/docs/reference/config/networking/v1alpha3/gateway/#Gateway[Istio documentation for gateways, window="_blank"]

[#destinationrules]
== Destination rules

=== Error message

More than one Destination Rule for the same host subset combination

=== Description

Istio applies traffic rules for services after the routing has happened. These can include different settings such as connection pooling, circuit breakers, load balancing, detection, etc. Istio can define the same rules for all services under a host or different rules for different versions of the service. 

This validation warning could be a result of duplicate definition of the same subsets as well as from rules that apply to all subsets. Also, a combination of one DR (Destination Rule) applying to all subsets and another defining behavior for only some subsets will trigger this validation warning.

Istio will silently ignore the duplicate subsets and merge these destination rules without letting the user know. Only the first seen rule (by Istio) per subset is used and information from multiple definitions is not merged. While the routing *might* work correctly, this is most likely a configuration error. It may lead to a undesired behavior if one of the offending rules is removed or modified and that is probably not the intention of the deployer of this service. Also, if the two offending destination rules have different policies for traffic routing the wrong one might be used.

=== Resolution

Either merge the settings to a single Destination Rule or split the subsets in such a way that they do not interleave. This ensures that the routing behavior stays consistent.

=== Severity

Warning

=== Example

[source, yaml]
----
include::/files/validation_examples/001.yaml
----

=== See Also

https://github.com/kiali/kiali/tree/master/business/checkers/destination_rules/multi_match_checker.go[Validator source code, window="_blank"]
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#DestinationRule[Destination rule documentation, window="_blank"]
https://github.com/istio/istio/blob/0e9cecab053aab744a7c3a731aacb07fd794d5f9/pilot/pkg/model/push_context.go#L879[Istio source code for merging, window="_blank"]
https://istio.io/help/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host[Istio documentation: Multiple virtual services and destination rules for the same host, window="_blank"]

'''
=== Error message

This host has no matching entry in the service registry (service, workload or service entries)

=== Description

Istio applies traffic rules for services after the routing has happened. These can include different settings such as connection pooling, circuit breakers, load balancing, detection, etc. Istio can define the same rules for all services under a host or different rules for different versions of the service. The host must a service that is defined in the platform's service registry or as a ServiceEntry. Short names are extended to include '.namespace.cluster' using the namespace of the destination rule, not the service itself. FQDN is evaluated as is. It is recommended to use the FQDN to prevent any confusion.

If the host is not found, Istio will ignore the defined rules.

=== Resolution

Correct the host to point to a correct service (in this namespace or with FQDN to other namespaces) or deploy the missing service to the mesh.

=== Severity

Error

=== Example

[source, yaml]
----
include::/files/validation_examples/002.yaml
----

=== See Also

https://github.com/kiali/kiali/tree/master/business/checkers/destination_rules/no_host_checker.go[Validator source code, window="_blank"]
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#DestinationRule[Destination rule documentation, window="_blank"]

'''

=== Error message

This subset’s labels are not found in any matching host

=== Description

Istio applies traffic rules for services after the routing has happened. These can include different settings such as connection pooling, circuit breakers, load balancing, detection, etc. Istio can define the same rules for all services under a host or different rules for different versions of the service. The host must a service that is defined in the platform's service registry or as a ServiceEntry. Short names are extended to include '.namespace.cluster' using the namespace of the destination rule, not the service itself. FQDN is evaluated as is. It is recommended to use the FQDN to prevent any confusion.

Subsets can override the global settings defined in the DR for a host. 

If the host is not found, Istio will ignore the defined rules.

=== Resolution

Correct the host to point to a correct service (in this namespace or with FQDN to other namespaces) or deploy the missing service to the mesh. If the hostname is equal to the one used otherwise in the DR, consider removing the duplicate host resolution.

Also, verify that the labels are correctly matching a workload with the intended service.

=== Severity

Error

=== Example

[source, yaml]
----
include::/files/validation_examples/003.yaml
----

=== See Also

https://github.com/kiali/kiali/tree/master/business/checkers/destination_rules/no_host_checker.go[Validator source code, window="_blank"]
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#DestinationRule[Destination rule documentation, window="_blank"]

'''
=== Error message

MeshPolicy enabling mTLS is missing

=== Description


=== Resolution


=== Severity

Error

=== Example

[source, yaml]
----
----

=== See Also


'''
=== Error message

mTLS settings of a non-local Destination Rule are overridden

=== Description


=== Resolution


=== Severity

Error

=== Example

[source, yaml]
----
----

=== See Also

'''
=== Error message

Policy enabling namespace-wide mTLS is missing

=== Description


=== Resolution


=== Severity

Error

=== Example

[source, yaml]
----
----

=== See Also


'''
=== Error message

Policy with TLS strict mode found, it should be permissive

=== Description


=== Resolution


=== Severity

Error

=== Example

[source, yaml]
----
----

=== See Also


'''
=== Error message

MeshPolicy enabling mTLS found, permissive policy is needed

=== Description


=== Resolution


=== Severity

Error

=== Example

[source, yaml]
----
----

=== See Also


'''

[#virtualservices]
== VirtualServices

=== Error message

DestinationWeight on route doesn't have a valid service (host not found)

=== Description

VirtualService will route matching requests to a service inside your mesh. Routing can also match a subset of traffic to a certain version of it for example. Any service inside the mesh must be targeted by its name, the IP address are only allowed for hosts defined through a Gateway. Host must be in a short name or FQDN format. Short name will evaluate to VS' namespace, regardless of where the actual service might be placed.

If the host is not found, Istio will ignore the defined rules. However, if a subset with a Destination Rule is not found it will affect all the subsets and all the routings. As such, care must be taken that the Destination rule is available before deploying the Virtual Service.

=== Resolution

Correct the host to point to a correct service (in this namespace or with FQDN to other namespaces), deploy the missing service to the mesh or remove the configuration linking to that non-existing service.

=== Severity

Error

=== Example

[source, yaml]
----
include::/files/validation_examples/102.yaml
----

=== See Also

https://github.com/kiali/kiali/tree/master/business/checkers/virtual_services/no_host_checker.go[Validator source code, window="_blank"]
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#Destination[Destination documentation, window="_blank"]

'''

=== Error message

VirtualService is pointing to a non-existent gateway

=== Description

By default, VirtualService routes will apply to sidecars inside the mesh. The gateway field allows to override that default and if anything is defined, the VS will only apply to those selected. 'mesh' is a reserved gateway name and means all the sidecars in the mesh. If one wishes to apply the VS to gateways as well as the sidecars, the 'mesh' keyword must be used as one of the gateways. Incorrect gateways will mean that the VS is not applied correctly.

=== Resolution

Fix the possible gateway field to target all necessary gateways or remove the field if the default 'mesh' is enough.

=== Severity

Error

=== Example

[source, yaml]
----
include::/files/validation_examples/101.yaml
----

=== See Also

https://github.com/kiali/kiali/tree/master/business/checkers/virtual_services/no_gateway_checker.go[Validator source code, window="_blank"]

'''

=== Error message

Subset not found

=== Description


=== Resolution


=== Severity

Error

=== Example

[source, yaml]
----
include::/files/validation_examples/105.yaml
----

=== See Also

https://github.com/kiali/kiali/tree/master/business/checkers/virtual_services/subset_presence_checker.go[source code, window="_blank"]

=== Error message

VirtualService doesn't define any route protocol

=== Description

VirtualService is a defined set of rules for routing certain type of traffic to target destinations with rules. At least one, 'tcp', 'http' or 'tls' must be defined. 

=== Resolution

This appears to be a configuration error. Fix the definition.

=== Severity

Error

=== Example

[source, yaml]
----
include::/files/validation_examples/103.yaml
----

=== See Also

https://github.com/istio/istio/blob/0e9cecab053aab744a7c3a731aacb07fd794d5f9/pilot/pkg/model/validation.go#L1628[Istio validation for route types, window="_blank"]
https://github.com/kiali/kiali/blob/master/business/checkers/virtual_services/no_host_checker.go[Validator source code, window="_blank"]

'''

=== Error message

More than one Virtual Service for same host

=== Description



=== Resolution

This is valid configuration only if VirtualService is bound to a gateway, sidecars do not accept this behavior. There are several caveats when using this method and defining the same parts in multiple Virtual Service definitions is not recommended. While Istio will merge the configuration, it does not guarantee any ordering for cross-resource merging and only the first seen configuration is applied (rest ignored). As recommended, each VS definition shold have a 'catch-all' situation, but this can only be defined in a definition affecting the same host. 

=== Severity

Warning

=== Example

[source, yaml]
----
include::/files/validation_examples/104.yaml
----

=== See Also

https://istio.io/help/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host[Istio documention Multiple virtual services for the same host, window="_blank"]

'''

=== Error message

Destination field is mandatory

=== Description



=== Resolution

=== Severity

Error

=== Example

[source, yaml]
----
include::/files/validation_examples/104.yaml
----

=== See Also

https://istio.io/help/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host[Istio documention Multiple virtual services for the same host, window="_blank"]

'''

[#services]
== Services

=== Error message

Port name must follow <protocol>[-suffix] form

=== Description

Istio requires the service ports to follow the naming form of 'protocol-suffix' where the '-suffix' part is optional. If the naming does not match this form (or is undefined), Istio treats all the traffic TCP instead of the defined protocol in the definition. Dash is a required character between protocol and suffix. For example, 'http2foo' is not valid, while 'http2-foo' is (for http2 protocol).

=== Resolution

Rename the service port name field to follow the form and the traffic will flow correctly. 

=== Severity

Error

=== Example

[source, yaml]
----
<TODO REQUIRES EXAMPLE>
----

=== See Also

https://github.com/kiali/kiali/blob/master/business/checkers/services/port_mapping_checker.go[Validator source code, window="_blank"]
https://github.com/istio/istio.io/blob/master/content/help/faq/traffic-management/naming-port-convention.md[Istio documentation port naming convention, window="_blank"]

'''

=== Error message

Service port and deployment port do not match

=== Description

Service definition has a combination of labels and port definitions that are not matching to any workloads. This means the deployment will be unsuccessful and no traffic can flow between these two resources.

=== Resolution

Fix the port definitions in the workload or in the service definition to ensure they match.

=== Severity

Error

=== Example

[source, yaml]
----
----

=== See Also

https://github.com/kiali/kiali/blob/master/business/checkers/services/port_mapping_checker.go[Validator source code, window="_blank"]


[#meshpolicies]
== Mesh Policies

=== Error message

Mesh-wide Destination Rule enabling mTLS is missing

=== Description


=== Resolution


=== Severity

Error

=== Example

[source, yaml]
----
include::/files/validation_examples/401.yaml
----

=== See Also

https://github.com/kiali/kiali/tree/master/business/checkers/mesh_policies_checker.go[Validator source code, window="_blank"]

[#serviceroles]
== ServiceRoles and ServiceRoleBindings

=== Error message

Unable to find all the defined services

=== Description

Services can be listed with an exact match, prefix match as well as suffix match. Using "*" refers to all the services in this namespace. This error indicates the services list is pointing to a service that can not be found from this namespace.

=== Resolution

Deploy the missing services or fix the services list to point to correct services.

=== Severity

Error

=== Example

[source, yaml]
----
----

=== See Also

https://github.com/kiali/kiali/blob/master/business/checkers/authorization/service_checker.go[Validator source code, window="_blank"]
https://istio.io/docs/reference/config/authorization/istio.rbac.v1alpha1/#AccessRule[Istio documentation, window="_blank"]

'''

=== Error message

ServiceRole can only point to current namespace

=== Description

Services can be listed with an exact match, prefix match as well as suffix match. Using "*" refers to all the services in this namespace. Although FQDN can be used, the namespace of the services must be the same as ServiceRole's deployment. 

=== Resolution

If the services in question are located in another namespace, deploy this ServiceRole to that namespace. Or deploy the services to this namespace.

=== Severity

Error

=== Example

[source, yaml]
----
----

=== See Also

https://github.com/kiali/kiali/blob/master/business/checkers/authorization/service_checker.go[Validator source code, window="_blank"]
https://istio.io/docs/reference/config/authorization/istio.rbac.v1alpha1/#AccessRule[Istio documentation, window="_blank"]

'''

=== Error message

ServiceRole does not exists in this namespace

=== Description

ServiceRoleBinding assigns a ServiceRole to subjects. As such, it must refer to a ServiceRole object and this object can only reside in the same namespace (cross-namespace refers are not valid).

=== Resolution

Deploy the missing ServiceRole to the same namespace.

=== Severity

Error

=== Example

[source, yaml]
----
----

=== See Also

https://github.com/kiali/kiali/blob/master/business/checkers/authorization/service_binding_checker.go[Validator source code, window="_blank"]
https://istio.io/docs/reference/config/authorization/istio.rbac.v1alpha1/#ServiceRoleBinding[Istio documentation, window="_blank"]

[#generic]

== Unknown

=== Error message

Unable to verify the validity, cross-namespace validation is not supported for this field

=== Description

In certain cases, Kiali is unable to validate the field since it spans another namespace to which the validator is not capable of looking at. In such cases, Kiali will mark this field with a grey icon indicating that the fields correctness could not be verified. This does not necessarily mean there is an error, but that the user should be careful and do the validation manually.

