---
title: "Prerequisites"
date: 2018-06-20T19:04:38+02:00
draft: false
type: "documentation"
weight: 2
---

= Prerequisites
:sectnums:
:toc: left
toc::[]
:toc-title: Prerequisites Content
:keywords: Kiali Documentation
:icons: font
:imagesdir: /images/documentation/prerequisites/

== Browser Requirements

Kiali requires a modern web browser to be able to function properly.

Users accessing Kiali should be doing so using the last two versions of Chrome, Edge, Firefox or Safari.

== Software Requirements

To run Kiali, you're going to need two things:

* A container platform, such as link:https://www.openshift.com/[Red Hat Openshift], link:https://okd.io[OKD] or link:https://kubernetes.io[Kubernetes]
* link:https://istio.io[Istio]
* link:https://github.com/jaegertracing/jaeger[Jaeger] is recommended to enable tracing features. It may be installed directly with Istio.

You can check on their respective documentations for installation steps. For
development environments, there's also
link:https://github.com/openshift-istio/origin[OpenShift Istio], which provides
`istiooc`, a quickstart tool that will help you get everything configured with
the least amount of hassle. You can get it link:https://github.com/openshift-istio/origin/releases[here].

== Hardware Requirements

Any machine capable of running OpenShift/OKD should be able to also run Kiali.
This usually means, for production environments:

* For masters: 16GB RAM, 4vCPUs, 40GB of hard disk space.
* For nodes: 8GB RAM, 1vCPU, 16GB of hard disk space.

You can find more information
link:https://docs.okd.io/latest/install/prerequisites.html[here].

For development, and using `oc cluster up`, the requirements are a little
lower, so 8GB of ram is usually ok, depending on how demanding your
applications are, and how many services you're planning on running at the same
time on your machine.  Of course, your mileage may vary, so plan accordingly.

Keep in mind that Kiali is not specially demanding of your machine resources,
and, as an isolated part of your environment, should not affect your
applications throughput and latency.
