#!/usr/bin/env bash
# Grafana Pod
GRAFANA_POD=$(kubectl get pod -n istio-system -l app=grafana -o=jsonpath={.items[*].metadata.name})
echo "Grafana port-forward"
echo "kubectl port-forward -n istio-system $GRAFANA_POD 13000:3000"
while true
do
    kubectl port-forward -n istio-system $GRAFANA_POD 13000:3000
    echo "Grafana connection lost, re-starting port-forward"
done
