#!/usr/bin/env bash
# Kiali Pod
KIALI_POD=$(kubectl get pod -n istio-system -l app=kiali -o=jsonpath={.items[*].metadata.name})
echo "Kiali port-forward"
echo "kubectl port-forward -n istio-system $KIALI_POD 9090:9090 --insecure-skip-tls-verify=false"
while true
do
    kubectl port-forward -n istio-system $KIALI_POD 9090:9090 --insecure-skip-tls-verify=false
    echo "Kiali connection lost, re-starting port-forward"
done
