---
title: "Contribute"
date: 2018-10-31T16:04:38+02:00
draft: false
menu:
  main:
    weight: 30
---

== Kiali is Open Source

Kiali is developed in the open under an https://www.apache.org/licenses/LICENSE-2.0.txt[Apache Software License version 2.0].
As such Kiali welcomes contributions in every form. 
This can be code, but also bug reports, feature requests, translations and much more.

Kiali source code is hosted at https://github.com/kiali[GitHub] with the two major repositories being:

* Kiali server -- https://github.com/kiali/kiali
* Kiali user interface -- https://github.com/kiali/kiali-ui

The source for this website is hosted at https://github.com/kiali/kiali.io

Please have a look at the README files in the repositories as well as the CONTRIBUTING.md ones.
Also make sure to check out the link:https://github.com/kiali/kiali/blob/master/CODE_OF_CONDUCT.md[Kiali code of conduct].

== Reporting issues and requesting features

The Kiali team uses link:https://github.com/kiali/kiali[kiali/kiali GitHub repository] as its centralized tracker.
Please use it to link:https://github.com/kiali/kiali/issues[report issues and request features]. When creating issues, please add the _bug_ or the _enhancement_ label as appropriate.

Issue tracking is also enabled for other Kiali repositories, like link:https://github.com/kiali/kiali.io[kiali/kiali.io] for the web page, and link:https://github.com/kiali/k-charted[kiali/k-charted] for the dashboards and some charts. You can report issues on these repositories if you know the issue is specific to that component. When in doubt, simply use the link:https://github.com/kiali/kiali[kiali/kiali repository].

== Talk with us

Kiali team has three preferred channels of contact:

* The link:https://groups.google.com/forum/#!forum/kiali-users[kiali-users Google Group], for end-user usage of Kiali. It's the preferred place to ask questions or expose problems you are having. Please, don't open GitHub issues for questions.
* The link:https://groups.google.com/forum/#!forum/kiali-dev[kiali-dev Google Group], for Kiali development. It's where discussions about Kiali contributions take place.
* The link:https://webchat.freenode.net/?channels=%23kiali[#kiali IRC channel at Freenode]. Wanna chat? Join us! This is where the Kiali team meets for more direct interaction.

Since Kiali is observability for Istio, you can also make contact through these Istio channels:

* link:https://discuss.istio.io/c/policies-and-telemetry/kiali[Istio's Discuss], where there is a dedicated Kiali _topic_.
* link:https://istio.slack.com/[Istio's Slack] where there is a dedicated _#kiali_ channel. Learn how to join Istio's Slack by visiting the _link:https://istio.io/about/community/join/[Getting Involved_ page of Istio's web site].

Istio's channels are alternative points of contact and we check them less often that the preferred channels.
