---
title: "Contribute"
date: 2018-10-31T16:04:38+02:00
draft: false
---

:sectlinks:
:icons: font

== Kiali is Open Source

Kiali is developed in the open under an https://www.apache.org/licenses/LICENSE-2.0.txt[Apache Software License version 2.0].
As such Kiali welcomes contributions in every form.
This can be code, but also bug reports, feature requests, translations and much more.

Kiali source code is hosted at https://github.com/kiali[GitHub] with the two major repositories being:

* Kiali server -- https://github.com/kiali/kiali
* Kiali user interface -- https://github.com/kiali/kiali-ui

The source for this website is hosted at https://github.com/kiali/kiali.io

Please have a look at the README files in the repositories as well as the CONTRIBUTING.md ones.
Also make sure to check out the link:https://github.com/kiali/kiali/blob/master/CODE_OF_CONDUCT.md[Kiali code of conduct].

== Reporting issues and requesting features

icon:exclamation-triangle[]{nbsp} Security issues should not be reported in a public way.  To report security issue please follow the steps described in the link:https://github.com/kiali/kiali/blob/master/SECURITY.md[Kiali Security Policy].

The Kiali team uses link:https://github.com/kiali/kiali[kiali/kiali GitHub repository] as its centralized tracker.
Please use it to link:https://github.com/kiali/kiali/issues[report issues and request features]. When creating issues, please add the _bug_ or the _enhancement_ label as appropriate.

Issue tracking is also enabled for other Kiali repositories, like link:https://github.com/kiali/kiali.io[kiali/kiali.io] for the web page, and link:https://github.com/kiali/k-charted[kiali/k-charted] for the dashboards and some charts. You can report issues on these repositories if you know the issue is specific to that component. When in doubt, simply use the link:https://github.com/kiali/kiali[kiali/kiali repository].

== Talk with us

There are several ways to contact, and be part of, the Kiali community:

* link:https://istio.slack.com/[Istio Slack] has a dedicated _#kiali_ channel. This is the best place to get both Kiali and Istio eyes on a question or comment. Learn how to join Istio Slack by visiting the _link:https://istio.io/latest/get-involved/[Get Involved_] page of Istio's web site.
* The link:https://web.libera.chat?channels=#kiali[#kiali IRC channel at Libera]. Join us for IRC chat, a great place for informal questions or comments!
* The link:https://github.com/kiali/kiali/discussions[Kiali Github Discussions]. Want to ask a more detailed question? To start or join a discussion, this is the place!
* The link:https://discuss.istio.io/c/policies-and-telemetry/kiali[Istio policies-and-telemetry on Discuss], where there is a dedicated Kiali _topic_.

== Community Calendar

Kiali has public community meetings every three weeks, at the end of each release. They happen on Friday at 10am (US/Eastern) / 4pm (Central Europe). Find these events and other major events on the https://bit.ly/kiali-calendar[Community Events calendar].

== Spread the word

As an open source project, community contributions are important to Kiali. The presence of Kiali in multiple projects and at conferences around the globe is a key for our continued success.
If you are organizing an event with presentations that include Kiali, we would love to know about it and help you spread the word. Please let us know by filling out this form:

++++
<div style="margin:auto;width:15%">
  <p class="buttons">
    <a href="https://bit.ly/3egKs58" class="button" target="_blank">
      Share your event
    </a>
  </p>
</div>
++++
