---
title: "Quick Start"
date: 2019-03-20T09:04:38+02:00
aliases:
- /quick-start
- /getting-started
- /gettingstarted
- /documentation/getting-started
- /documentation/latest/getting-started
draft: false
weight: 2
---

:toc: macro
:toclevels: 2
:toc-title: Table of Contents
:keywords: Kiali Quick Start
:icons: font
:imagesdir: /images/quickinstall/
:sectlinks:

You can quickly install and try Kiali via one of the following two methods.

WARNING: These instructions are not recommended for
production environments. Find more detailed information on installing Kiali,
see the link:{{< ref "/documentation/staging/installation-guide"
>}}[installation guide].

== Install via Istio Addons

If you link:https://istio.io/latest/docs/setup/getting-started/#download[downloaded Istio], the easiest way to install and try Kiali is by running:

[source,bash]
----
kubectl apply -f ${ISTIO_HOME}/samples/addons/kiali.yaml
----

To uninstall:

[source,bash]
----
kubectl delete -f ${ISTIO_HOME}/samples/addons/kiali.yaml --ignore-not-found
----

== Install via Helm 

WARNING: Only Helm v3 has been tested. Previous Helm versions may or may not work.

To install the latest version of Kiali Server using link:https://helm.sh/[Helm], run the following command:

[source,bash]
----
helm install \
  --namespace istio-system \
  --set auth.strategy="anonymous" \
  --repo https://kiali.org/helm-charts \
  kiali-server \
  kiali-server
----

NOTE: If you get a validation error, you may have to pass the option `--disable-openapi-validation` (this is needed on OpenShift 4.5, for example).

To uninstall:

[source,bash]
----
helm uninstall --namespace istio-system kiali-server
----


== Access to the UI

Run the following command:

[source,bash]
----
kubectl port-forward svc/kiali 20001:20001 -n istio-system
----

Then, access Kiali by visiting \https://localhost:2001/ in your preferred web browser.


