---
title: "Concepts"
date: 2018-06-20T19:04:38+02:00
draft: false
---

= Kiali Concepts Glossary
:sectnums:
:toc: left
toc::[]
:toc-title: Terminology Content
:keywords: Kiali Documentation
:icons: font
:imagesdir: /images/documentation/terminology/

== Application

Is a logical grouping of <<Workload>>s defined by the application labels that users apply to an object. In Istio it is defined by the <<Label App>>. link:https://istio.io/docs/setup/kubernetes/spec-requirements/[Istio Label Requirements].

=== Application Name

It's the name of the <<Application>> deployed in your environment. This name is provided by the <<Label App>> on the <<Workload>>.

== Deployment

A deployment is a replication controller based on a user defined template called a <<Deployment>> configuration. Deployments are created manually or in response to triggered events.

=== Istio object/configuration Type

This is the type specified in the <<Istio Config>>. This could be any of the following types: <<Gateway>>, <<VirtualService>>, <<DestinationRule>>, <<ServiceEntry>>, <<Rule>>, <<QuotaSpec>> or <<QuotaSpecBinding>>.

== Istio Sidecar

For more information see the <<Istio Sidecar>> definition in link:https://istio.io/docs/reference/commands/sidecar-injector/[Istio Sidecar Documentation].

== Label

It's a user-created tag to identify a set of objects.

An empty link:https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[label selector] (that is, one with zero requirements) selects every object in the collection.

A null link:https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[label selector] (which is only possible for optional selector fields) selects no objects.

For example, Istio uses the <<Label App>> & <<Label Version>> on a <<Workload>> to specify the version and the application.

=== Label App

This is the 'app' label on an object. For more information, see the link: link:https://istio.io/docs/setup/kubernetes/spec-requirements/[Istio Label Requirements].

=== Label Version

This is the 'version' label on an object. For more information, see the link: link:https://istio.io/docs/setup/kubernetes/spec-requirements/[Istio Label Requirements].


== Namespace

Namespaces are intended for use in environments with many users spread across multiple teams, or projects.

Namespaces are a way to divide cluster resources between multiple users.

== Quota

A limited or fixed number or amount of resources.

== QuotaSpecBinding

Quota spec binding is used to bind link:https://istio.io/help/faq/mixer/[mixer] quota resource name to a proxy.

== ReplicaSet

Ensures that a specified number of pod replicas are running at any one time.

== Service

A <<Service>> is an abstraction which defines a logical set of Pods and a policy by which to access them.  A Service is determined by a <<Label>>.

=== Service Entry

For more information see the <<Service Entry>> definition in link:https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry[Istio Service Entry Documentation].

== VirtualService

For more information see the <<VirtualService>> definition in link:https://istio.io/docs/reference/config/istio.networking.v1alpha3/#VirtualService[Istio VirtualService Documentation].

== Workload

For more information see the <<Workload>> definition in link:https://istio.io/help/glossary/#workload[Istio Glossary].

=== Workload Type

It's the type of the <<Workload>>, Kiali currently supports the <<Deployment>> type.
