name: Docs Linter (textlint)

on:
  pull_request:
    branches: [ staging, current ]

jobs:
  textlint:
    name: textlint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install --no-save textlint textlint-rule-preset-ja-technical-writing textlint-rule-no-todo


      - name: Run textlint
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: warning
          textlint_flags: "content/**/*.md"          
