name: Pull Metrics

on:
  workflow_dispatch:
  schedule:
  # Every week at 00:00 on Sunday
    - cron: "0 0 * * 0"
permissions: read-all

jobs:
  build:
    permissions:
      contents: write  # needs to commit metrics.json and push to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

      - name: setup python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c  # v4
        with:
          python-version: '3.10' # install the python version needed      
      - name: install python packages
        run: |          
          python -m pip install --upgrade pip
          pip install -r scripts/api_gh/requirements.txt

      - name: execute py script # run main.py
        env:
          KIALI_API_TOKEN: ${{ secrets.KIALI_API_TOKEN }}
        run: make generate_metrics_json
      - name: Configure git
        run: |
          git config user.email 'kiali-dev@googlegroups.com'

          git config user.name 'kiali-bot'         
      - name: Update metrics file
        run: |
          if [[ `git status --porcelain` ]]; then
            echo -e "\e[1;32mOK\e[0m \e[1;39mMetrics json change detected.\e[0m"
            git add content/en/community/data/metrics.json
            git commit -m "Update Community data: metrics.json"
            git push origin
          else
            echo -e "\e[1;39mNo changes were detected.\e[0m"
          fi
        shell: bash  

      - name: Update events
        run: |
          echo "Updating"   
          make generate_event_json      

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f  # v4
        with:
          branch: gh-pages
          folder: website/build          